name: GHA-reuse-code-checkout.yml
on: 
  workflow_call: 
  workflow_dispatch: 
  
jobs:
    Image-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: list the files
              run: |
               ls -lrt
               echo test
               echo values.yml
               pwd 